### ISSUE TITLE
Hey !

### ISSUE THREAD

**Issue by itsN1X** [MozillaTN/mozillatn.github.io#125]
I need you to allow me write: access for contributing into Mozilla TN sources directly. Also, I request you to as me as a member @MozillaTN . I have previously been added as a contributor by @iamVP7 
Thanks

**Comment by iamVP7** [comment]
@itsN1X  I dont see the need as of now giving Write access to you for this repo. I hope for you already there is repo github.com/mozillatn/vit please let me know the reason in detail. Ping in telegram to discuss in detail. Telegram handle: @iamvp7
