### ISSUE TITLE
Change the folder struct

### ISSUE THREAD

**Issue by iamVP7** [MozillaTN/mozillatn.github.io#133]
We have to create sub folder inside _posts so we will have posts ordered properly like 2016->team_name->filename instead of what is present now

**Comment by prasanthp96** [comment]
cool will work on that

**Comment by iamVP7** [comment]
For my Personal blog, I am using the struct like this you can take a look at my [repo](https://github.com/iamVP7/iamVP7.github.io/tree/master/_posts)

**Comment by prasanthp96** [comment]
sure @iamVP7 bro.

**Comment by prasanthp96** [comment]
Have created a branch and implemented the same .. @iamVP7 kindly review it bro.

https://github.com/MozillaTN/mozillatn.github.io/tree/FileStructureChange

**Comment by prasanthp96** [comment]
Changes [commited](https://github.com/MozillaTN/mozillatn.github.io/commit/0142d662a0954bd7749263fe11a4e3907e647114) successfully.
