### ISSUE TITLE
Updating Status of SUMO Links

### ISSUE THREAD

**Issue by iamVP7** [MozillaTN/mozillatn.github.io#32]
Task Owner: @hellokarthic 

Doc to update : https://docs.google.com/spreadsheets/d/1STdV1cmwPV96Mk_i17lqtvgHrGoujMvTJ_pvFAJjXNc/edit#gid=506648884

Contributors Updated Fully
- [ ] @roopaksuresh
- [ ] @123survesh 
- [ ] @prasanthp96 
- [ ] @paarttipaabhalaji
- [ ] @Ashlyrose
- [ ] @Makilan 
- [ ] @BhuvanaMeenakshi 
- [ ] @dineshkumareswaran
- [ ] @fahidroid
- [ ] @Manokarr
- [ ] @Madhukanth

**Comment by iamVP7** [comment]
Just checking with all trainers (@roopaksuresh @123survesh @prasanthp96 @paarttipaabhalaji @Ashlyrose @Makilan @BhuvanaMeenakshi @dineshkumareswaran @fahidroid @Manokarr @Madhukanth ) .. if you have done please comment.. so @hellokarthic  can write the final consolidated blog post..

**Comment by BhuvanaMeenakshi** [comment]
I will confirm it tonight

With Regards,
Ms. K. Bhuvana Meenakshi,
B.E. (III-Year),
Computer Science and Engineering,
Dhirajlal Gandhi College of Technology,
Salem.

**Comment by 123survesh** [comment]
confirm what?

**Comment by iamVP7** [comment]
@123survesh just whether your team done with sumo.

**Comment by BhuvanaMeenakshi** [comment]
The completion status of SUMO

On Aug 20, 2016 8:15 PM, Survesh Jones notifications@github.com wrote:
confirm what?
