### ISSUE TITLE
Add a favicon 

### ISSUE THREAD

**Issue by abhi12ravi** [MozillaTN/mozillatn.github.io#6]

**Comment by dvigneshwer** [comment]
Do we have an official logo for Mozilla Tamil Nadu?

**Comment by abhi12ravi** [comment]
Not yet, but we should really make one! 
Open up a contest maybe? Something very specific to Tamil Nadu and Tamil.

**Comment by dvigneshwer** [comment]
That's definitely an ideal solution :+1:

**Comment by nkarthic95** [comment]
Favicon Added in all pages.

**Comment by abhi12ravi** [comment]
Cool, looks fine for now. We'll change it once the logo is made. Thank you!

On Sat, May 30, 2015 at 1:34 PM, Karthic Keyan <notifications@github.com>
wrote:

> Favicon Added in all pages.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MozillaTN/mozillatn.github.io/issues/6#issuecomment-107006803>
> .
>



-- 
Regards,
Abhiram Ravikumar
http://abhiramrk.com/
