### ISSUE TITLE
MozillaTN Index page Designs

### ISSUE THREAD

**Issue by iamVP7** [MozillaTN/mozillatn.github.io#91]
Submit your Designs as comments. You can invite your friends to add reactions to your designs.

Remember to check the following
- For sure we want the last 3 or 5 posts made by contributors.
- Space to Share Latest Firefox download link.
- Space to share our Social Links.
- Share important resources links based on Functional areas.

Submission Closes on: 15th Dec 2016
Voting Closes on : 20th Dec 2016

Join at Telegram: @mozillatn @mozillatnc to have great conversation and ideas to design and get clarified your doubts.

**Comment by blahatrohit** [comment]
![wireframehighfed](https://cloud.githubusercontent.com/assets/20833109/20859959/455d16a8-b993-11e6-8532-993dcdd6912e.jpg)

Here by Submitting my redesign concept.
-rohit raj

**Comment by nirmal-gl** [comment]
![mozilla site design](https://cloud.githubusercontent.com/assets/13619793/20867769/0e6e24c2-ba72-11e6-82d7-cdd893a3b461.jpg)
By nirmal gl

**Comment by lokeshwaran97** [comment]
![mozilla tn](https://cloud.githubusercontent.com/assets/22743076/20969780/6cc8cea4-bc3f-11e6-81bb-35aa27db23eb.png)
by lokeshwaran

**Comment by manojanbarasu97** [comment]
well done lokesh...keep it up

**Comment by RUDDHIKA** [comment]
Great job lokesh ...All the best 👍

**Comment by iamVP7** [comment]
Closing this. Will continue talking with @rohitrrcr  @nirmal-gl  @lokeshwaran97  in closed chat for designing.
